# Welcome to Jekyll!
#

# Site settings
title: Mariage Célia et Arnaud
description: |
  Le 12 septembre 2020  
  Thonon-les-Bains  
  Haute-Savoie
update_title: Le grand jour arrive
update_date: "Dernière mise à jour : 22/08/2019"
update_description: |
  Ca y est, nous entrons dans le vif du sujet et lançons l'organisation de notre mariage le 12 septembre 2020 !
    
  Après la cérémonie officielle à la mairie de Thonon-les-Bains, non loin du lac Léman, la fête se poursuivra au pied des montagnes, dans le domaine de la Ferme du Château. Gardez bien ce site en favoris car nous le mettrons à jour avec toutes les informations nécessaires.  
  
  A bientôt  
  Célia et Arnaud
owner: Arnaud Décolasse
first_published: 2019 # if migrating another site, the year of your first publish
email: arnaud.decolasse@gmail.com
baseurl: "" # the subpath of your site, e.g. /mariage
url: "https://www.mariage-celia-arnaud.fr" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
#sass:
#  style: compressed
