# Welcome to Jekyll!
#

# Site settings
title: Mariage Célia et Arnaud
description: |
  Le 12 septembre 2020  
  Thonon-les-Bains  
  Haute-Savoie
owner: Arnaud Décolasse # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: arnaud.decolasse@gmail.com
baseurl: "/mariage" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
#sass:
#  style: compressed
